apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: jenkins
  template:
    metadata: 
      labels: 
        app: jenkins
    spec: 
      serviceAccountName: jenkins-sa
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
          - name: jenkins-storage
            mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-storage
        persistentVolumeClaim:
          claimName: jenkins-pvc
